#|

based on 103d105 with these changes:

  removed mrspidey prims, turtle prims, eval, eval-string, pretty-print parameters
  moved assignment, ho prims to advanced

|#


(module lang-names mzscheme
  (provide beginner-names intermediate-adds advanced-adds)
  
  (define beginner-names
    '(*
      /
      =
      <
      >
      <=
      current-seconds
      e
      complex?
      empty
      sinh
      square
      denominator
      and
      posn-x
      posn-y
      exact->inexact
      inexact->exact
      cond
      remainder
      number->string
      string->number
      or
      filename-extension
      make-directory*
      equal?
      make-string
      string-length
      char-alphabetic?
      string-ci=?
      exit
      char-upper-case?
      string-ci<?
      char-lower-case?
      string-ci>?
      conjugate
      string-ci<=?
      string-ci>=?
      string-append
      string->list
      list->string
      make-posn
      char-numeric?
      char->integer
      integer->char
      char-upcase
      char-downcase
      build-list
      compose
      char-whitespace?
      remove*
      seventh
      regexp-match-exact?
      symbol=?
      build-absolute-path
      define-values
      delete-directory/files
      file-name-from-path
      values
      void?
      posn?
      null
      pair?
      cons
      car
      null?
      list*
      length
      append
      memv
      member
      symbol?
      cadr
      caddr
      reverse
      cadddr
      list-ref
      boolean=?
      real?
      exact?
      odd?
      even?
      gcd
      lcm
      floor
      round
      exp
      log
      sin
      cos
      number?
      tan
      asin
      acos
      rational?
      atan
      integer?
      sqrt
      expt
      inexact?
      angle
      add1
      sub1
      ceiling
      abs
      numerator
      modulo
      make-polar
      real-part
      imag-part
      magnitude
      zero?
      quotient
      max
      min
      random
      error
      cons?
      eighth
      empty?
      false
      fifth
      eof
      read
      first
      path-only
      format
      fourth
      char?
      char=?
      char<?
      char>?
      not
      eq?
      rec
      nor
      lambda
      quote
      remv
      string?
      remv*
      rest
      second
      string-ref
      third
      string=?
      true
      string<?
      string>?
      last-pair
      string<=?
      string>=?
      substring
      case-lambda
      char<=?
      char>=?
      char-ci=?
      char-ci<?
      char-ci>?
      char-ci<=?
      char-ci>=?
      boolean?
      raise
      char->string
      +
      >=
      if
      identity
      evcase
      cosh
      sgn
      remq*
      explode-path
      pi
      define
      merge-input
      define-constructor
      read-from-string
      find-relative-path
      dynamic-enable-break
      define-struct
      ignore-errors
      struct?
      remove
      recur
      read-from-string-all
      nand
      build-relative-path
      make-temporary-file
      sixth
      expr->string
      newline-string
      find-library
      normalize-path
      dynamic-disable-break
      void
      consumer-thread
      cdr
      list?
      list
      memq
      assq
      local
      foldl
      remq
      -))
  
  (define intermediate-adds
    '(time
      let 
      let*-values
      unquote-splicing
      let-struct
      letrec
      let*
      letrec-values
      let-values
      unquote
      quasiquote
      ))
  
  (define advanced-adds
    '(loop-until
      with-semaphore
      semaphore-wait-multiple
      make-semaphore
      procedure?
      assf
      mergesort
      set-cdr!
      string-copy
      string-lowercase!
      string-uppercase!
      append!
      filter
      foldr
      time-apply
      memf
      apply
      printf
      pretty-print
      display
      case
      delay
      let/ec
      do
      when
      fluid-let
      make-vector
      vector-length
      vector-set!
      make-promise
      map
      ormap
      build-string
      build-vector
      call/cc
      set-car!
      box
      box?
      unbox
      set-box!
      write
      vector
      set!
      begin
      begin0
      force
      vector?
      vector-ref
      promise?
      parameterize
      unless
      move
      let/cc
      set-posn-x!
      set-posn-y!
      set!-values
      call-with-current-continuation
      with-handlers
      display-lines-in-drawing
      andmap
      for-each
      quicksort))
  
  (define turtles-names
    '(split
      split*
      tprompt
      clear
      turtles
      draw
      draw-offset
      turn
      save-turtle-bitmap
      turtle-window-size
      splitfn
      split*fn
      erase
      turn/radians
      move-offset
      erase-offset)))